#---- begin snakebids boilerplate ----------------------------------------------

import snakebids
from snakebids import bids

from pathlib import Path
from scripts.mp2rage_genUniDen.mp2rage_genUniDen import mp2rage_genUniDen
from os.path import join

configfile: workflow.source_path('../config/snakebids.yml')

# Get input wildcards
inputs = snakebids.generate_inputs(
    bids_dir=config["bids_dir"],
    pybids_inputs=config["pybids_inputs"],
    pybids_database_dir=config.get("pybids_db_dir"),
    pybids_reset_database=config.get("pybids_db_reset"),
    derivatives=config.get("derivatives", None),
    participant_label=config.get("participant_label", None),
    exclude_participant_label=config.get("exclude_participant_label", None),
    use_bids_inputs=True,
)



#this adds constraints to the bids naming
wildcard_constraints:  **snakebids.get_wildcard_constraints(config['pybids_inputs'])

#---- end snakebids boilerplate ------------------------------------------------

rule grad_correction:
    input: 
        bids_dir = config['bids_dir'],
        grad_coef_file = config['grad_coeff_file'],
    params:
        grad_corr_dir = bids(
            root = 'derivatives',
            suffix = 'gradcorrect'
        ),
        gradcorrect_script = join(workflow.basedir,'../workflow/scripts/gradcorrect/run.sh')
    output: 
        done = bids(
            root='work',
            datatype='gradcorrect',
            suffix = 'gradcorr.done',
            **inputs.subj_wildcards
            )
    container: config['singularity']['gradcorrect']
    group: 'subj'
    threads: 8
    resources:
        mem_mb = 16000,
        time = 180
    log: bids(root='logs',suffix='gradcorrect.log',**inputs.subj_wildcards)
    shell:
        """
        {params.gradcorrect_script} {input.bids_dir} {params.grad_corr_dir} participant --grad_coeff_file {input.grad_coef_file} --participant_label {wildcards.subject} &> {log}
        touch {output.done}
        """ 

rule mp2rage_correction:
    input: 
        grad_corr_done = rules.grad_correction.output.done,
    params:
        grad_corr_dir = bids(
            root = 'derivatives',
            suffix = 'gradcorrect'
        ),
        mp2rage_correction_dir = bids(
            root = 'derivatives',
            suffix = 'mp2rage_correction',
        ),
        mp2rage_correction_script = join(workflow.basedir,'../workflow/scripts/mp2rage_correction/mp2rage_correction')
    output:
        done = bids(
            root = 'work',
            datatype = 'mp2rage_correction',
            suffix = 'mp2rage_corr.done',
            **inputs.subj_wildcards
        ),
    container: config['singularity']['mp2rage_correction']
    group: 'subj'
    threads: 8
    resources:
        mem_mb = 16000,
        time = 180
    log: bids(root='logs',suffix='mp2ragecorr.log',**inputs.subj_wildcards)
    shell:
        """
        {params.mp2rage_correction_script} {params.grad_corr_dir} {params.mp2rage_correction_dir}  participant --participant_label {wildcards.subject} &> {log}
        touch {output.done}
        """ 

# rule gen_t1w:
#     input:
#         mp2rage_correction_done = rules.mp2rage_correction.output.done,
#     params:
#         mp2rage_correction_dir = bids(
#             root = 'derivatives',
#             suffix = 'mp2rage_correction'
#         ),
#         gen_t1w_script= join(workflow.basedir,'../workflow/scripts/mp2rage_genUniDen/mp2rage_genUniDen.py'),
#         get_paths_script = join(workflow.basedir,'../workflow/scripts/gen_t1w_paths.py')
#     output:
#         t1w_output = bids(
#             root = 'derivatives/gen_t1w',
#             datatype = 'anat',
#             acq = 'genUNIDEN',
#             suffix = 'T1w.nii.gz',
#             **inputs.subj_wildcards
#         )
#     group: 'subj'
#     threads: 8
#     resources:
#         mem_mb = 16000,
#         time = 180
#     log: bids(root='logs',suffix='gent1w.log',**inputs.subj_wildcards)   
#     shell:
#         """
#         uni=$(python {params.get_paths_script} {params.mp2rage_correction_dir} {wildcards.subject} "uni") &> {log}
#         inv1=$(python {params.get_paths_script} {params.mp2rage_correction_dir} {wildcards.subject} "inv1") &> {log}
#         inv2=$(python {params.get_paths_script} {params.mp2rage_correction_dir} {wildcards.subject} "inv2") &> {log}
        
#         python {params.gen_t1w_script} "$uni" "$inv1" "$inv2" {output.t1w_output} &> {log}
#         """


# rule qsm_sstv:
#     input: 
#         grad_corr = rules.grad_correction.output.done
#     params:
#         qsm_sstv = bids(
#             root = 'derivative',
#             suffix = 'qsm_sstv'
#         )
#     output:
#         done = touch(bids(
#             root = 'work',
#             datatype = 'qsm_sstv',
#             suffix = 'qsm_sstv.done',
#             **inputs.subj_wildcards
#         )),
#     group: 'subj'        
#     container: config['singularity']['qsm_sstv']
#     shell:
#         """
#         qsm_sstv
#         """

rule synthstrip:
    input:
        mp2rage_correction_done = rules.mp2rage_correction.output.done,
    params:
        container_path = config['singularity']['synthstrip'],
        synthstrip_script = join(workflow.basedir,'../workflow/scripts/synthstrip-singularity'),
        get_paths_script = join(workflow.basedir,'../workflow/scripts/gen_t1w_paths.py'),
        mp2rage_correction_dir = bids(
            root = 'derivatives',
            suffix = 'mp2rage_correction',
        ),
    output: 
        skstrip = bids(
            root = 'derivatives/synthstrip',
            datatype = 'anat',
            acq = 'genUNIDEN',
            desc = 'sythstrip',
            suffix = 'T1w.nii.gz',
            **inputs.subj_wildcards
        ),
        mask = bids(
            root = 'derivatives/synthstrip',
            datatype = 'anat',
            acq = 'genUNIDEN',
            desc = 'brainmask',
            suffix = 'T1w.nii.gz',
            **inputs.subj_wildcards
        )
    group: 'subj'
    threads: 8
    resources:
        mem_mb = 16000,
        time = 180
    log: bids(root='logs',suffix='sythstrip.log',**inputs.subj_wildcards)  
    shell:
        """
        t1w_path=$(python {params.get_paths_script} {params.mp2rage_correction_dir} sub-{wildcards.subject})
        echo $t1w_path &> {log}
        python {params.synthstrip_script} {params.container_path} -i $t1w_path -o {output.skstrip} -m {output.mask} &> {log}
        """ 


# rule mri_qc:
#     input: 
#         mp2rage_correction_dir = bids(
#             root = 'results',

#         )
#     output:
#     container:config['singularity']['mri_qc'] 
#     shell: 
#         """
        
#         """

rule all:
    input:
        # expand(
        #     rules.gen_t1w.output.t1w_output,
        #     zip,
        #     **inputs.input_zip_lists['scans_tsv']
        # ),
        expand(
            rules.synthstrip.output.mask,
            zip,
            **inputs.input_zip_lists['scans_tsv']
        )
    default_target: True